module.exports = {
	name: "dsl.1und1.de", // optional, falls back to object key
	description: "dsl.1und1.de",
	options: {
		frequency: 60 * 23, // (in minutes), 23 hours
	},
	urls: [
		"https://dsl.1und1.de/",
		"https://dsl.1und1.de/wlan-router",
		"https://dsl.1und1.de/fritzbox",
		"https://dsl.1und1.de/dsl-verfuegbarkeit",
		"https://dsl.1und1.de/dsl-ohne-vertragslaufzeit",
		"https://dsl.1und1.de/vdsl-verfuegbarkeit",
		"https://dsl.1und1.de/heimvernetzung",
		"https://dsl.1und1.de/telefonflat",
		"https://dsl.1und1.de/mobile-dsl-flat",
		"https://dsl.1und1.de/dsl-preisvergleich",
		"https://dsl.1und1.de/dsl-tarif-vergleich",
		"https://dsl.1und1.de/fernsehen",
		"https://dsl.1und1.de/highspeed-netz",
		"https://dsl.1und1.de/dsl-umzug",
		"https://dsl.1und1.de/dsl-tarife",
		"https://dsl.1und1.de/vorteils-aktion",
		"https://dsl.1und1.de/powerline-wlan-aus-der-steckdose",
		"https://dsl.1und1.de/wlan-repeater",
		"https://dsl.1und1.de/dsl-garantie",
		"https://dsl.1und1.de/shopsuche",
		"https://dsl.1und1.de/dsl-anbieter",
		"https://dsl.1und1.de/dsl-angebote",
		"https://dsl.1und1.de/dsl-anschluss",
		"https://dsl.1und1.de/dsl-kaufen",
		"https://dsl.1und1.de/dsl-vertrag",
		"https://dsl.1und1.de/guenstiger-internetanbieter",
		"https://dsl.1und1.de/internet-bestellen",
		"https://dsl.1und1.de/internet-flatrate",
		"https://dsl.1und1.de/router-mit-telefonanlage",
		"https://dsl.1und1.de/telefon-und-internet-flat",
		"https://dsl.1und1.de/wlan-stick",
		"https://dsl.1und1.de/surfen-im-internet",
		"https://dsl.1und1.de/schnelles-internet",
		"https://dsl.1und1.de/young",
		"https://dsl.1und1.de/business",
		"https://dsl.1und1.de/glasfaser",
		"https://dsl.1und1.de/gigabit",
		"https://dsl.1und1.de/gigabit-lan",
		"https://dsl.1und1.de/glasfaser-bandbreite",
		"https://dsl.1und1.de/glasfaserkabel",
		"https://dsl.1und1.de/glasfaser-internet-anbieter",
		"https://dsl.1und1.de/glasfaserausbau",
		"https://dsl.1und1.de/glasfasernetz",
		"https://dsl.1und1.de/glasfaser-router",
		"https://dsl.1und1.de/glasfaser-anbieter-wechsel",
		"https://dsl.1und1.de/glasfaserleitung",
		"https://dsl.1und1.de/glasfaseranbindung",
		"https://dsl.1und1.de/glasfaseranbieter",
		"https://dsl.1und1.de/glasfaser-anbieter-vergleich",
		"https://dsl.1und1.de/aktion-sharp-uhd-tv-40",
		"https://dsl.1und1.de/aktion-lg-uhd-tv-55",
		"https://dsl.1und1.de/aktion-ipad-10-2",
		"https://dsl.1und1.de/aktion-hp-255-g7",
		"https://dsl.1und1.de/smart-home",
		"https://dsl.1und1.de/wlan-versprechen",
		"https://dsl.1und1.de/funktionsgarantie",
		"https://dsl.1und1.de/priority-hotline",
		"https://dsl.1und1.de/wlan-planer"
	]
};
